FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY app/ ./app/
COPY alembic.ini .
COPY alembic/ ./alembic/
COPY entrypoint.sh .
COPY static/ ./static/
RUN chmod +x entrypoint.sh
CMD ["/bin/sh", "entrypoint.sh"]